export const projects = [
  {
    active: true,
    name: "Servu",
    repo: "https://github.com/mohsenfallahnjd/servu",
    description: "Never miss a service again. Log oil changes, filters, brakes, and every periodic service for your vehicles — simple, private, and always at hand.",
    demo: "https://servu-app.vercel.app/",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind", "Vercel", "PostgreSQL", "Prisma", "NextAuth.js"],
  },
  {
    active: true,
    name: "Qistly",
    repo: "https://github.com/mohsenfallahnjd/qist",
    description: "Never miss a payment again. Track loans, installments, and recurring payments. See what you owe this month, mark them paid, move on.",
    demo: "https://qistly.vercel.app/",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind", "Vercel", "Neon Postgres"],
  },
  {
    active: true,
    name: "Birthday Reminder",
    repo: "https://github.com/mohsenfallahnjd/birthday-reminder",
    description:
      "Never forget a birthday again. A simple app to track and get reminded of your friends and family birthdays.",
    demo: "https://wishdayapp.vercel.app/",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind"],
  },
  {
    active: true,
    name: "PDF Briefer",
    repo: "https://github.com/mohsenfallahnjd/pdf-briefer",
    description:
      "Upload a PDF and get an AI-powered summary. Quickly extract key insights from documents without reading them in full.",
    demo: "https://pdf-briefer.vercel.app/",
    technologies: ["Next.js", "React", "TypeScript", "AI"],
  },
  {
    active: true,
    name: "Fun Mun",
    repo: "https://github.com/mohsenfallahnjd/fun-mun",
    description: "A fun and interactive application built for entertainment and engagement.",
    demo: "https://fun-mun.vercel.app/",
    technologies: ["JavaScript", "React"],
  },
  {
    active: true,
    name: "Kodous",
    repo: "https://github.com/mohsenfallahnjd/kodous",
    description: "A minimal service to send appreciation (kudos) to your team. Simple, kind, and personal.",
    demo: "https://kodous.vercel.app/",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind", "Vercel", "Neon Postgres"],
  },
  {
    active: true,
    name: "Alias Router Pro (Chrome Extension)",
    repo: "https://github.com/mohsenfallahnjd/alias-router-pro",
    description:
      "A Chrome extension that allows you to create aliases for your URLs. like go + abc-123 => https://example.com/abc-123",
    demo: "https://chromewebstore.google.com/detail/alias-router-pro-omnibox/jlcfcckgpagmgggcjnlljejkbplcfjbh",
    technologies: ["JavaScript", "HTML", "Chrome Extension", "Omnibox"],
  },
  {
    active: true,
    name: "Bitlyst",
    repo: "https://github.com/mohsenfallahnjd/bitlyst",
    description:
      "A minimal, fast, and beautiful blog built with Next.js 15, designed for sharing bite-sized tech tips and insights. Perfect for developers who want to quickly publish short, focused content.",
    demo: "https://bitlyst.vercel.app/",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind", "Vercel"],
  },
  {
    active: true,
    name: "Scrum Poker",
    repo: "https://github.com/mohsenfallahnjd/scrum-poker",
    description:
      "A modern, interactive Planning Poker application built with Next.js and Framer Motion. This tool helps agile teams estimate story points using fun, illustrated cards with Persian translations.",
    demo: "https://mohsenfallahnjd.github.io/scrum-poker/",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind"],
  },
  {
    active: true,
    name: "Markdown Reader",
    description: "Paste or upload any markdown and get a clean, readable view instantly. No setup, no sign-up.",
    repo: "https://github.com/mohsenfallahnjd/markdown-reader",
    demo: "https://md-reader-kappa.vercel.app/",
  },
  {
    active: true,
    name: "Paymay",
    description: "Track shared expenses and split bills with friends. Simple and fair.",
    repo: "https://github.com/mohsenfallahnjd/paymay",
    demo: "https://paymay-dun.vercel.app/",
  },
  {
    active: true,
    name: "React Query Mock Data",
    repo: "https://github.com/mohsenfallahnjd/react-query-mock-data",
    description:
      "A powerful and flexible package for generating mock data in React applications using React Query. This package provides hooks that make it easy to generate realistic mock data for testing and development purposes.",
    demo: "https://www.npmjs.com/package/react-query-mock-data",
    technologies: ["TypeScript", "React Query"],
  },
  {
    active: true,
    name: "Mood Snap",
    repo: "https://github.com/mohsenfallahnjd/mood-snap",
    description:
      "A simple, privacy-focused daily mood tracking application built with Next.js. Track your emotional well-being with just one click and visualize your mood trends over time.",
    demo: "https://moodsnap.me",
    technologies: ["TypeScript", "React", "Next.js", "Tailwind", "chart.js"],
  },
  {
    active: true,
    name: "Gitlab Notify",
    repo: "https://github.com/mohsenfallahnjd/gitlabnotify",
    description: "Get gitlab merge requests notification on your telegram",
    demo: "",
    technologies: ["javascript"],
  },
  {
    active: true,
    name: "Spotify api wrapper",
    repo: "https://github.com/mohsenfallahnjd/spotify-api-wrapper",
    description: "A wrapper base on node.js for working spotify api",
    technologies: ["nodejs", "express"],
  },
  {
    active: true,
    name: "You Don't Know JS Yet",
    repo: "https://github.com/mohsenfallahnjd/ydkjs-vuepress",
    description: "You Don't Know JS Yet (book series) - 2nd Edition by vuepress.",
    technologies: ["vite", "Vuepress"],
  },
];
