export const services = [
  {
    id: "birthday-reminder",
    name: "Birthday Reminder",
    problem: "You always remember birthdays... the day after.",
    solution: "Get notified before it's too late. Simple, private, no fluff.",
    href: "https://wishdayapp.vercel.app/",
    cta: "Try it free",
    color: "#ff6b6b",
    icon: "🎂",
    tags: ["Reminders", "Free"],
  },
  {
    id: "pdf-briefer",
    name: "PDF Briefer",
    problem: "Nobody has time to read a 40-page PDF for 3 key points.",
    solution: "Drop a PDF, get a crisp AI summary in seconds.",
    href: "https://pdf-briefer.vercel.app/",
    cta: "Summarize now",
    color: "#0000ff",
    icon: "📄",
    tags: ["AI", "Productivity"],
  },
  {
    id: "fun-mun",
    name: "Fun Mun",
    problem: "The internet is too serious sometimes.",
    solution: "An interactive playground. Jump in and see what happens.",
    href: "https://fun-mun.vercel.app",
    cta: "Play now",
    color: "#7c3aed",
    icon: "🎮",
    tags: ["Fun", "Interactive"],
  },
  {
    id: "bitlyst",
    name: "Bitlyst",
    problem: "Medium is bloated. Twitter is too short. You need a middle ground.",
    solution: "A minimal, fast blog for short focused dev tips. No noise.",
    href: "https://bitlyst.vercel.app/",
    cta: "Read now",
    color: "#059669",
    icon: "✍️",
    tags: ["Blog", "Dev"],
  },
  {
    id: "markdown-reader",
    name: "Markdown Reader",
    problem: "Raw markdown is unreadable. Opening an editor just to preview is overkill.",
    solution: "Paste any markdown, get a clean readable view instantly. No setup.",
    href: "https://md-reader-kappa.vercel.app/",
    cta: "Open reader",
    color: "#d97706",
    icon: "📝",
    tags: ["Utility", "Free"],
  },
  {
    id: "paymay",
    name: "Paymay",
    problem: "Group trips end in awkward \"who owes who\" moments.",
    solution: "Track shared expenses and split bills fairly. No awkwardness.",
    href: "https://paymay-dun.vercel.app/",
    cta: "Split now",
    color: "#0891b2",
    icon: "💸",
    tags: ["Finance", "Social"],
  },
  {
    id: "quiet-floor",
    name: "Quiet Floor",
    problem: "Remote work is lonely, but video calls are exhausting.",
    solution: "A virtual office to set focus status and work alongside others — no calls, just presence.",
    href: "https://quiet-floor.vercel.app",
    cta: "Enter the floor",
    color: "#64748b",
    icon: "🏢",
    tags: ["Focus", "Remote"],
  },
  {
    id: "scrum-poker",
    name: "Scrum Poker",
    problem: "Story point debates drag standups into hour-long meetings.",
    solution: "Planning poker for agile teams. Reveal cards together, align faster.",
    href: "https://mohsenfallahnjd.github.io/scrum-poker/",
    cta: "Start session",
    color: "#7c3aed",
    icon: "🃏",
    tags: ["Agile", "Free"],
  },
  {
    id: "alias-router-pro",
    name: "Alias Router Pro",
    problem: "You visit the same URLs daily and still type the full address every time.",
    solution: "Create short aliases for any URL. Type `go docs` in the omnibox, land instantly.",
    href: "https://chromewebstore.google.com/detail/alias-router-pro-omnibox/jlcfcckgpagmgggcjnlljejkbplcfjbh",
    cta: "Install extension",
    color: "#ea4335",
    icon: "⚡",
    tags: ["Chrome", "Productivity"],
  },
];
