export const skills = [
  { name: "React", color: "#61dafb" },
  { name: "Next.js", color: "#111" },
  { name: "TypeScript", color: "#3178c6" },
  { name: "JavaScript", color: "#c9a800" },
  { name: "Vue.js", color: "#42b883" },
  { name: "Tailwind", color: "#38bdf8" },
  { name: "MUI", color: "#0081cb" },
  { name: "Framer Motion", color: "#bb4b96" },
  { name: "Node.js", color: "#339933" },
  { name: "Figma", color: "#f24e1e" },
  { name: "MongoDB", color: "#47a248" },
  { name: "Git", color: "#f05032" },
  { name: "Docker", color: "#2496ed" },
  { name: "Sass", color: "#cc6699" },
  { name: "HTML", color: "#e34f26" },
  { name: "CSS", color: "#1572b6" },
];
